### ISSUE TITLE
possible to port to android?

### ISSUE THREAD

**Issue by kcochibili** [PrismaNano/TicTacToe3D#10]
Hello, I wanna know if it is possible for this game to be converted to an android game. if possible, how?

**Comment by PrismaNano** [comment]
My knowledge concerning programming for android devices is limited although I strongly believe a version of this game can be coded for android.

**Comment by jadaradix** [comment]
You can get a Nintendo DS emulator for Android. That's the easiest and best way to play the game on a phone. The code written here will not be useful for creating an Android game (wrong language... by a mile; designed for 2 screens; specific library dependant), and you would have to start from line 0 to write it. You'd need a new project altogether. (recommend writing in HTML5 so you can run it anywhere...!)

**Comment by PrismaNano** [comment]
Cool, nice to know Android can support playing DS games through an emulator.

**Comment by kcochibili** [comment]
I am saddened by this.
I remember playing this game.  Bringing it back to life on android would have been fun for me.  I dont know html, or C, rather I only know java. so I guess i'd have to go research the possibility of recreating the game using openGL.
