### ISSUE TITLE
Graphic Binaries

### ISSUE THREAD

**Issue by jadaradix** [PrismaNano/TicTacToe3D#3]
You have the .bin files for graphics in the repo, but not the originals (PNGs?). You are somehow converting the originals to .bin, so you should document that, include the originals and if you make the conversion a part of the build process, you can remove the .bin files from the repo as well.

The eventual aim is that the repo contains only source code and not "resultant files" from a build. So, if you build the project, there are no changes to commit.

**Comment by PrismaNano** [comment]
I had to convert each file individually since dsgmlib does not automatically convert graphics for you.

**Comment by CTurt** [comment]
I have adapted the dsgmLib examples to include the unconverted graphics, as well as the ini file needed to convert them.

I have placed some of the graphics in the gfx directory, but it is still missing the models and textures, please upload them PrismaNano.

**Comment by PrismaNano** [comment]
Is it the raw .3ds models you want? Would there be functionality in dsgmlib to convert models and textures too?

**Comment by CTurt** [comment]
From now on, I am going with the philosophy that everything used should be included in its original form, as well as instructions (PAGfx.ini file for example) of how it was converted.

This means that anyone can modify your models and graphics in the true spirit of open source.

**Comment by PrismaNano** [comment]
I used the NDS_Model_Exporter tool that came with the Nitro Engine lib to convert the .3ds models to .bin.

**Comment by jadaradix** [comment]
Good work on getting the PAGfx ini in there, but it would be nice to document how to "run this" (PAGfx). Better yet, get it in the Makefile as part of the build process! CTurt can help you with that.

**Comment by CTurt** [comment]
The issue with automating this process it that it is not clear for each project whether the graphics should be stored in the "data" directory (to be loaded from RAM) or the "nitrofiles" directory (to be loaded from NitroFS). This could be stored in the PAGfx.ini file, but it seems to be something that should ideally be handled by a GUI.
