### ISSUE TITLE
Tic Tac Toe  3D Screenshots

### ISSUE THREAD

**Issue by PrismaNano** [PrismaNano/TicTacToe3D#4]
![ticktacktoe3d](https://cloud.githubusercontent.com/assets/12837982/8222251/872bc172-1536-11e5-98a4-35ed755c9d39.png)

**Comment by CTurt** [comment]
Not an issue.

**Comment by CTurt** [comment]
Using the new camera angle:

![](http://cturt.github.io/images/dsgmLib/tickTackToe3D.png)

**Comment by PrismaNano** [comment]
![tictactoe3d_logo](https://cloud.githubusercontent.com/assets/12837982/8603371/acf00f06-2645-11e5-8375-9ac7d08b5790.png)

**Comment by jadaradix** [comment]
You should host these elsewhere, or on a "GitHub Pages" site (should allow hotlinking!): https://pages.github.com/

You'll then be able to use source control for the website itself.

**Comment by CTurt** [comment]
I went ahead and setup a GitHub pages for this project:

http://prismanano.github.io/TicTacToe3D/

**Comment by PrismaNano** [comment]
Meh I don't really care...how do you use that link?

**Comment by CTurt** [comment]
Upload images and web pages to the gh-pages branch:

https://github.com/PrismaNano/TicTacToe3D/tree/gh-pages

**Comment by PrismaNano** [comment]
![tic tac toe 3d ad](https://cloud.githubusercontent.com/assets/12837982/9126246/1f212288-3c79-11e5-8f05-bf6bff04e33b.png)

![screenshot](https://cloud.githubusercontent.com/assets/12837982/9126261/4c1e59ae-3c79-11e5-8291-be4aec5d51b8.png)

Posting these here until I figure out how to push to gh-pages
