### ISSUE TITLE
Fix Zoom Slider

### ISSUE THREAD

**Issue by PrismaNano** [PrismaNano/TicTacToe3D#7]
...or replace it with buttons instead. Need to work on getting the camera to translate smoothly using the slider.

**Comment by CTurt** [comment]
Fixed. The View_X variable is a float, so you should divide by another float or else it will be treated as integer division.

I'd prefer that you didn't use floats at all, and just used bitshifts, but I'll leave it up to you if you'd like to change it.

See the change here:

https://github.com/PrismaNano/TicTacToe3D/commit/3bfd9d4852eaf69702843c1334cce1c589247b7f#diff-9b8d0255f3473595a948dfba0db509f3R957
